---
title: "4_forecast"
author: "Federico Dallo"
date: "3/3/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Forecast

Reference: <https://otexts.com/fpp3/>

The predictability of an event or a quantity depends on several factors including:

1- how well we understand the factors that contribute to it;
2- how much data is available;
3- how similar the future is to the past;
4- whether the forecasts can affect the thing we are trying to forecast.

### Example 4.1

Predict tomorrow sunrise, predict tomorrow lotto numbers

"Once it has been determined what forecasts are required, it is then necessary to find or collect the data on which the forecasts will be based. The data required for forecasting may already exist. These days, a lot of data are recorded, and the forecaster’s task is often to identify where and how the required data are stored. The data may include sales records of a company, the historical demand for a product, or the unemployment rate for a geographic region. A large part of a forecaster’s time can be spent in locating and collating the available data prior to developing suitable forecasting methods."

## Qualitative forecasting

When there are no data and we have to find a better than "guesswork".

## Quantitative forecasting

When:

- numerical information about the past is available;
- it is reasonable to assume that some aspects of the past patterns will continue into the future.









